# Questions 1:

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [4]:
import numpy as np
arr= np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2:

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [9]:
A=[11,25,3,4,5]
B=[6,77,8,69,10]
arr1=np.array(A)
arr2=np.array(B)


In [11]:
#list A copnverted to array.
arr1

array([11, 25,  3,  4,  5])

In [12]:
#list B converted to array
arr2

array([ 6, 77,  8, 69, 10])

In [13]:
a=np.concatenate((arr1,arr2)) #array concatenation
a

array([11, 25,  3,  4,  5,  6, 77,  8, 69, 10])

In [15]:
np.sort(a) #sorting of concatenated array

array([ 3,  4,  5,  6,  8, 10, 11, 25, 69, 77])

# Question 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [16]:
b=np.ndarray([3,4,2]) #ndarray
b

array([[[2.31297541e-312, 2.35541533e-312],
        [2.46151512e-312, 2.33419537e-312],
        [2.31297541e-312, 2.56761491e-312],
        [2.05833592e-312, 6.79038654e-313]],

       [[2.37663529e-312, 2.05833592e-312],
        [2.41907520e-312, 6.79038653e-313],
        [2.37663529e-312, 2.05833592e-312],
        [2.05833592e-312, 2.18565567e-312]],

       [[8.48798317e-313, 9.33678148e-313],
        [1.01855798e-312, 1.08221785e-312],
        [2.12199579e-313, 2.41907520e-312],
        [1.42410974e-306, 8.34451927e-308]]])

In [17]:
np.ndim(b) #dimension of ndarray

3

In [18]:
np.size(b) #size of ndarray

24

# Question 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [19]:
a1 = np.arange(4)
a1.shape

(4,)

In [20]:
row_vec = a1[np.newaxis, :]     # arr[None, :]
row_vec.shape

(1, 4)

In [21]:
row_vec #1D array

array([[0, 1, 2, 3]])

In [22]:
col_vec = a1[:, np.newaxis]     # arr[:, None]
col_vec.shape

(4, 1)

In [23]:
col_vec #converted to 2D array using np.newaxis

array([[0],
       [1],
       [2],
       [3]])

In [24]:
#Converting 1D array to 2D array using np.expand_dims
a1

array([0, 1, 2, 3])

In [25]:
np.ndim(a1)

1

In [26]:
a2 = np.expand_dims(a1, axis=(1,-2,3))
a2.shape

(4, 1, 1, 1)

In [27]:
np.ndim(a2)

4

# Question 5:

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [28]:
f = np.array([1,2,3])
g = np.array([4,5,6])  

print('Horizontal Append:\n', np.hstack((f, g))) #using hstack()

Horizontal Append:
 [1 2 3 4 5 6]


In [29]:

f = np.array([1,2,3])
g = np.array([4,5,6])  

print('Vertical Append:\n', np.vstack((f, g)))  #using vstack()

Vertical Append:
 [[1 2 3]
 [4 5 6]]


# Question 6:

How to get unique items and counts of unique items?